# BASIC STATISTICS-2

### Problem Statement : Hospital Patient Data Analysis

Context:
A hospital maintains patient records including admission details, department, diagnosis, doctor, and bill amount. You have two datasets: one with patient info and another with billing details. Some patients have blank bill amounts, and there are multiple rows for the same patient due to follow-ups.

##### Tasks:

1.	Load the patient dataset and show summary with info().
2.	Select only the columns relevant for billing: ['PatientID', 'Department', 'Doctor', 'BillAmount'].
3.	Drop administrative columns like ['ReceptionistID', 'CheckInTime'].
4.	Use groupby to find total bill amount per department.
5.	Remove duplicate patient records based on PatientID.
6.	Fill missing BillAmount values with the mean bill amount.
7.	Merge the billing dataset with patient dataset on PatientID.
8.	Concatenate an additional DataFrame that contains new patients for the current week (row-wise).
9.	Concatenate new billing category columns like ['InsuranceCovered', 'FinalAmount'] (column-wise).

In [108]:
import pandas as pd

In [109]:
# 1.	Load the patient dataset and show summary with info().
patient_df = pd.read_csv(r'Dataset\Patient_Data.csv')
patient_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   PatientID       6 non-null      int64
 1   Name            6 non-null      object
 2   Department      6 non-null      object
 3   Doctor          6 non-null      object
 4   BillAmount      4 non-null      float64
 5   ReceptionistID  6 non-null      int64
 6   CheckInTime     6 non-null      object
dtypes: float64(1), int64(2), object(4)
memory usage: 468.0+ bytes

In [110]:
# 2.	Select only the columns relevant for billing: ['PatientID', 'Department', 'Doctor', 'BillAmount'].
patient_df[['PatientID', 'Department', 'Doctor', 'BillAmount']]

   PatientID   Department     Doctor  BillAmount
0        101   Cardiology  Dr. Smith      5000.0
1        102    Neurology   Dr. John         NaN
2        103  Orthopedics    Dr. Lee      7500.0
3        104   Cardiology  Dr. Smith      6200.0
4        105  Dermatology   Dr. Rose         NaN
5        101   Cardiology  Dr. Smith      5000.0

In [111]:
# 3.	Drop administrative columns like ['ReceptionistID', 'CheckInTime'].
patient_df.drop(columns=['ReceptionistID', 'CheckInTime'],inplace=True)

In [112]:
patient_df.head()

   PatientID     Name   Department     Doctor  BillAmount
0        101    Alice   Cardiology  Dr. Smith      5000.0
1        102      Bob    Neurology   Dr. John         NaN
2        103  Charlie  Orthopedics    Dr. Lee      7500.0
3        104    David   Cardiology  Dr. Smith      6200.0
4        105      Eva  Dermatology   Dr. Rose         NaN

In [113]:
# 4.	Use groupby to find total bill amount per department.
patient_df.groupby('Department')['BillAmount'].sum().reset_index()

    Department  BillAmount
0   Cardiology     16200.0
1  Dermatology         0.0
2    Neurology         0.0
3  Orthopedics      7500.0

In [114]:
# 5.	Remove duplicate patient records based on PatientID.
patient_df.drop_duplicates(inplace=True)
patient_df.duplicated().sum()

np.int64(0)

In [115]:
# 6.	Fill missing BillAmount values with the mean bill amount.
patient_df['BillAmount'] = patient_df['BillAmount'].fillna(patient_df['BillAmount'].mean()).round(1)
patient_df

   PatientID     Name   Department     Doctor  BillAmount
0        101    Alice   Cardiology  Dr. Smith      5000.0
1        102      Bob    Neurology   Dr. John      6233.3
2        103  Charlie  Orthopedics    Dr. Lee      7500.0
3        104    David   Cardiology  Dr. Smith      6200.0
4        105      Eva  Dermatology   Dr. Rose      6233.3

In [116]:
# 7.	Merge the billing dataset with patient dataset on PatientID.
billing_df = pd.read_csv(r"Dataset\Billing_Data.csv")
billing_df

   PatientID  InsuranceCovered  FinalAmount
0        101              2000         3000
1        102              1500         3500
2        103              2500         5000
3        104              3000         3200
4        105              1000         4000

In [117]:
merged_df = pd.merge(patient_df,billing_df,on='PatientID')
merged_df

,PatientID,Name,Department,Doctor,BillAmount,InsuranceCovered,FinalAmount
0,101,Alice,Cardiology,Dr. Smith,5000.0,2000,3000
1,102,Bob,Neurology,Dr. John,6233.3,1500,3500
2,103,Charlie,Orthopedics,Dr. Lee,7500.0,2500,5000
3,104,David,Cardiology,Dr. Smith,6200.0,3000,3200
4,105,Eva,Dermatology,Dr. Rose,6233.3,1000,4000

In [118]:
patient_df

   PatientID     Name   Department     Doctor  BillAmount
0        101    Alice   Cardiology  Dr. Smith      5000.0
1        102      Bob    Neurology   Dr. John      6233.3
2        103  Charlie  Orthopedics    Dr. Lee      7500.0
3        104    David   Cardiology  Dr. Smith      6200.0
4        105      Eva  Dermatology   Dr. Rose      6233.3

In [119]:
# 8.	Concatenate an additional DataFrame that contains new patients for the current week (row-wise).
new_patients_data = {
    "PatientID":['106',"107"],
	'Name':['Kavee','Sriman'],
	'Department':['Cardiology','Neurology'],
	'Doctor':['Dr. Smith','Dr. John'],
	'BillAmount':['10000','11000'],
}
new_patients_df = pd.DataFrame(new_patients_data)
merged_df = pd.concat([patient_df,new_patients_df],axis=0,ignore_index=True)
merged_df

  PatientID     Name   Department     Doctor BillAmount
0       101    Alice   Cardiology  Dr. Smith     5000.0
1       102      Bob    Neurology   Dr. John     6233.3
2       103  Charlie  Orthopedics    Dr. Lee     7500.0
3       104    David   Cardiology  Dr. Smith     6200.0
4       105      Eva  Dermatology   Dr. Rose     6233.3
5       106    Kavee   Cardiology  Dr. Smith      10000
6       107   Sriman    Neurology   Dr. John      11000

In [122]:
# 9. Concatenate new billing category columns like ['InsuranceCovered', 'FinalAmount'] (column-wise).
merged_final_df = pd.concat([merged_df, billing_df[['InsuranceCovered', 'FinalAmount']]], axis=1)
merged_final_df['InsuranceCovered'] = merged_final_df['InsuranceCovered'].fillna(merged_final_df['InsuranceCovered'].mean())
merged_final_df['FinalAmount'] = merged_final_df['FinalAmount'].fillna(merged_final_df['FinalAmount'].mean())
merged_final_df

,PatientID,Name,Department,Doctor,BillAmount,InsuranceCovered,FinalAmount
0,101,Alice,Cardiology,Dr. Smith,5000.0,2000.0,3000.0
1,102,Bob,Neurology,Dr. John,6233.3,1500.0,3500.0
2,103,Charlie,Orthopedics,Dr. Lee,7500.0,2500.0,5000.0
3,104,David,Cardiology,Dr. Smith,6200.0,3000.0,3200.0
4,105,Eva,Dermatology,Dr. Rose,6233.3,1000.0,4000.0
5,106,Kavee,Cardiology,Dr. Smith,10000,2000.0,3740.0
6,107,Sriman,Neurology,Dr. John,11000,2000.0,3740.0

### Outcome
*	Final cleaned dataset with accurate billing info.
*	All missing values handled, merged dataset across PatientID.
*	Ability to perform further analytics on department-wise revenue or doctor performance.